name: variant-remapping
channels:
  - bioconda
  - defaults
dependencies:
  - bedtools=2.29.2
  - bowtie2=2.4.1
  - samtools=1.4.1-0 
  - bcftools=1.9 
  - bedops=2.4.39
  - tabix=0.2.6
  - pysam=0.15.4s 
  - biopython=1.76
